# Generated by Django 3.2.8 on 2021-10-17 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Adresse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Af',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Af', models.IntegerField()),
                ('mont_If', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_Debut', models.DateTimeField()),
                ('d_Fin', models.DateTimeField()),
                ('obsIf', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Commune', models.IntegerField()),
                ('c_Grade', models.CharField(max_length=10)),
                ('comF', models.CharField(max_length=40)),
                ('comA', models.CharField(max_length=40)),
                ('obsComm', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Grade', models.IntegerField(max_length=1)),
                ('c_Grade', models.CharField(max_length=10)),
                ('gradF', models.CharField(max_length=40)),
                ('gradA', models.CharField(max_length=40)),
                ('obsGrad', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Pays', models.IntegerField()),
                ('c_Pays', models.CharField(max_length=10)),
                ('paysF', models.CharField(max_length=40)),
                ('paysA', models.CharField(max_length=40)),
                ('obsPays', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=8, null=True)),
                ('nom', models.CharField(max_length=190, null=True)),
                ('prenom', models.CharField(max_length=190, null=True)),
                ('d_naissance', models.DateTimeField()),
                ('l_naissance', models.CharField(max_length=190, null=True)),
                ('d_created', models.DateField(auto_now_add=True, null=True)),
                ('d_Modified', models.DateField(auto_now_add=True, null=True)),
                ('active_Person', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('obsPerson', models.CharField(max_length=200, null=True)),
                ('sexe', models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Situation', models.CharField(max_length=4)),
                ('obsSit', models.CharField(max_length=200, null=True)),
                ('grade', models.ManyToManyField(to='GestionAuxiliaires.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Conjoint',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionAuxiliaires.person')),
                ('cin_Conjoint', models.CharField(max_length=8, null=True)),
            ],
            bases=('GestionAuxiliaires.person',),
        ),
        migrations.CreateModel(
            name='Enf',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionAuxiliaires.person')),
                ('cin_Parent', models.CharField(max_length=8, null=True)),
            ],
            bases=('GestionAuxiliaires.person',),
        ),
        migrations.CreateModel(
            name='Ref',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='GestionAuxiliaires.person')),
                ('mle', models.IntegerField()),
                ('phone', models.CharField(max_length=190, null=True)),
                ('photo', models.ImageField(blank=True, default='preson.png', null=True, upload_to='')),
                ('d_recrut', models.DateTimeField(null=True)),
            ],
            bases=('GestionAuxiliaires.person',),
        ),
        migrations.CreateModel(
            name='Tb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Tb', models.IntegerField()),
                ('mont_Tb', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_Debut', models.DateTimeField()),
                ('d_Fin', models.DateTimeField()),
                ('obsTb', models.CharField(max_length=200, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Taux_Anc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_Anc', models.CharField(max_length=190, null=True)),
                ('m_Anc', models.DecimalField(decimal_places=2, max_digits=5)),
                ('obsTA', models.CharField(max_length=200, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Solde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tba', models.DecimalField(decimal_places=2, max_digits=6)),
                ('anca', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ifa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ira', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ita', models.DecimalField(decimal_places=2, max_digits=6)),
                ('afa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ba', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rcars', models.DecimalField(decimal_places=2, max_digits=6)),
                ('amo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('caad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('igr', models.DecimalField(decimal_places=2, max_digits=6)),
                ('netm', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rcarp', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cnops', models.DecimalField(decimal_places=2, max_digits=6)),
                ('obsSit', models.CharField(max_length=200, null=True)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
            ],
        ),
        migrations.AddField(
            model_name='situation',
            name='taux_Anc',
            field=models.ManyToManyField(to='GestionAuxiliaires.Taux_Anc'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Region', models.IntegerField()),
                ('c_Region', models.CharField(max_length=10)),
                ('regionF', models.CharField(max_length=40)),
                ('regionA', models.CharField(max_length=40)),
                ('obsRegion', models.CharField(max_length=200, null=True)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.pays')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Quartier', models.IntegerField()),
                ('c_Quartier', models.CharField(max_length=10)),
                ('quartF', models.CharField(max_length=40)),
                ('quartA', models.CharField(max_length=40)),
                ('obsQuart', models.CharField(max_length=200, null=True)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Prefecture', models.IntegerField()),
                ('c_Pref', models.CharField(max_length=10)),
                ('prefF', models.CharField(max_length=40)),
                ('prefA', models.CharField(max_length=40)),
                ('obsPref', models.CharField(max_length=200, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.region')),
            ],
        ),
        migrations.CreateModel(
            name='It',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_It', models.IntegerField()),
                ('mont_It', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_Debut', models.DateTimeField()),
                ('d_Fin', models.DateTimeField()),
                ('obsIt', models.CharField(max_length=200, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade')),
            ],
        ),
        migrations.CreateModel(
            name='Ir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Ir', models.IntegerField()),
                ('mont_Ir', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_Debut', models.DateTimeField()),
                ('d_Fin', models.DateTimeField()),
                ('obsIr', models.CharField(max_length=200, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade')),
            ],
        ),
        migrations.CreateModel(
            name='If',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_If', models.IntegerField()),
                ('mont_If', models.DecimalField(decimal_places=2, max_digits=7)),
                ('d_Debut', models.DateTimeField()),
                ('d_Fin', models.DateTimeField()),
                ('obsIf', models.CharField(max_length=200, null=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='pref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.prefecture'),
        ),
        migrations.CreateModel(
            name='Autre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_Autre', models.IntegerField()),
                ('AutreF', models.CharField(max_length=80, null=True)),
                ('AutreA', models.CharField(max_length=80, null=True)),
                ('obsAutre', models.CharField(max_length=200, null=True)),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='adresse',
            name='commune',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.commune'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='prefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.prefecture'),
        ),
        migrations.AddField(
            model_name='adresse',
            name='quartier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier'),
        ),
        migrations.AddField(
            model_name='situation',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.ref'),
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_Effet', models.DateTimeField()),
                ('d_fin_eng', models.DateTimeField()),
                ('d_deb_rap', models.DateTimeField()),
                ('d_fin_rap', models.DateTimeField()),
                ('objet', models.CharField(max_length=255)),
                ('obsPerio', models.CharField(max_length=200, null=True)),
                ('active_Periode', models.BooleanField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.ref')),
            ],
        ),
    ]
