# Generated by Django 3.2.9 on 2021-12-26 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAuxiliaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_debut', models.DateField()),
                ('d_fin', models.DateField()),
                ('objet', models.CharField(max_length=255)),
                ('active_interval', models.BooleanField()),
                ('obsIntrval', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_type', models.CharField(max_length=10)),
                ('l_type', models.CharField(max_length=100)),
                ('obsType', models.CharField(default='RAS', max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='autre',
            old_name='AutreA',
            new_name='autreA',
        ),
        migrations.RenameField(
            model_name='autre',
            old_name='AutreF',
            new_name='autreF',
        ),
        migrations.RenameField(
            model_name='commune',
            old_name='c_Grade',
            new_name='c_Commune',
        ),
        migrations.RenameField(
            model_name='solde',
            old_name='rcars',
            new_name='rcar',
        ),
        migrations.RemoveField(
            model_name='adresse',
            name='code_Adresse',
        ),
        migrations.RemoveField(
            model_name='af',
            name='d_Debut',
        ),
        migrations.RemoveField(
            model_name='af',
            name='d_Fin',
        ),
        migrations.RemoveField(
            model_name='af',
            name='id_Af',
        ),
        migrations.RemoveField(
            model_name='autre',
            name='code_Autre',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='code_Commune',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='code_Grade',
        ),
        migrations.RemoveField(
            model_name='if',
            name='d_Debut',
        ),
        migrations.RemoveField(
            model_name='if',
            name='d_Fin',
        ),
        migrations.RemoveField(
            model_name='if',
            name='id_If',
        ),
        migrations.RemoveField(
            model_name='ir',
            name='d_Debut',
        ),
        migrations.RemoveField(
            model_name='ir',
            name='d_Fin',
        ),
        migrations.RemoveField(
            model_name='ir',
            name='id_Ir',
        ),
        migrations.RemoveField(
            model_name='it',
            name='d_Debut',
        ),
        migrations.RemoveField(
            model_name='it',
            name='d_Fin',
        ),
        migrations.RemoveField(
            model_name='it',
            name='id_It',
        ),
        migrations.RemoveField(
            model_name='pays',
            name='code_Pays',
        ),
        migrations.RemoveField(
            model_name='periode',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='person',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='person',
            name='cin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prefecture',
            name='code_Prefecture',
        ),
        migrations.RemoveField(
            model_name='quartier',
            name='code_Quartier',
        ),
        migrations.RemoveField(
            model_name='region',
            name='code_Region',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='taux_Anc',
        ),
        migrations.RemoveField(
            model_name='tb',
            name='d_Debut',
        ),
        migrations.RemoveField(
            model_name='tb',
            name='d_Fin',
        ),
        migrations.RemoveField(
            model_name='tb',
            name='id_Tb',
        ),
        migrations.AddField(
            model_name='conjoint',
            name='cin',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='cin',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ref',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation',
            name='code_taux_anc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.taux_anc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='situation',
            name='nbre_enf',
            field=models.PositiveSmallIntegerField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solde',
            name='objet',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='taux_anc',
            name='code_taux_anc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='periode',
            name='d_Effet',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periode',
            name='d_deb_rap',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periode',
            name='d_fin_eng',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='periode',
            name='d_fin_rap',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='d_naissance',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='l_naissance',
            field=models.CharField(default='Mohammedia', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='obsPerson',
            field=models.CharField(default='RAS', max_length=4),
        ),
        migrations.AlterField(
            model_name='ref',
            name='d_recrut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='situation',
            name='c_Situation',
            field=models.CharField(max_length=6),
        ),
        migrations.RemoveField(
            model_name='situation',
            name='grade',
        ),
        migrations.AddField(
            model_name='situation',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.grade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Sm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Sm', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='SitFin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.periode')),
                ('sit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
            ],
        ),
        migrations.CreateModel(
            name='Rue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rueF', models.CharField(max_length=80, null=True)),
                ('rueA', models.CharField(max_length=80, null=True)),
                ('obsrue', models.CharField(max_length=200, null=True)),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Residence', models.CharField(max_length=10)),
                ('resF', models.CharField(max_length=40)),
                ('resA', models.CharField(max_length=40)),
                ('obsRes', models.CharField(max_length=200, null=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Rcar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Rcar', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='NetM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_NetM', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='Lotissement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_Lotissement', models.CharField(max_length=10)),
                ('lotF', models.CharField(max_length=40)),
                ('lotA', models.CharField(max_length=40)),
                ('obsLot', models.CharField(max_length=200, null=True)),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='interval',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.type'),
        ),
        migrations.CreateModel(
            name='Igr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Igr', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='Caad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Caad', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='BruteM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_BruteM', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.CreateModel(
            name='Boulevard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdF', models.CharField(max_length=80, null=True)),
                ('bdA', models.CharField(max_length=80, null=True)),
                ('obsBd', models.CharField(max_length=200, null=True)),
                ('quart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.quartier')),
            ],
        ),
        migrations.CreateModel(
            name='Amo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_Amo', models.DecimalField(decimal_places=2, max_digits=3)),
                ('c_Situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.situation')),
                ('code_Interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval')),
            ],
        ),
        migrations.AddField(
            model_name='af',
            name='code_Periode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='if',
            name='code_Interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ir',
            name='code_Interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='it',
            name='code_Interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periode',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ref',
            name='sitFin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.sitfin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb',
            name='code_Interval',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.interval'),
            preserve_default=False,
        ),
    ]
