# Generated by Django 3.2.9 on 2021-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAuxiliaires', '0002_auto_20211226_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
    ]
