# Generated by Django 3.2.9 on 2021-12-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAuxiliaires', '0003_alter_person_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='sexe',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1),
        ),
    ]
