# Generated by Django 3.2.9 on 2021-12-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAuxiliaires', '0009_alter_person_sexe'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitfin',
            name='periode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.periode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='sexe',
            field=models.CharField(choices=[('F', 'Feminin'), ('M', 'Masculin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sitfin',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionAuxiliaires.type'),
        ),
    ]
