# Generated by Django 3.2.9 on 2021-12-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAuxiliaires', '0010_auto_20211229_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interval',
            name='active_interval',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='objet',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='type',
        ),
        migrations.RemoveField(
            model_name='solde',
            name='objet',
        ),
        migrations.AlterField(
            model_name='autre',
            name='obsAutre',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='boulevard',
            name='obsBd',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='commune',
            name='comA',
            field=models.CharField(default='RAS', max_length=40),
        ),
        migrations.AlterField(
            model_name='grade',
            name='obsGrad',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='if',
            name='obsIf',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='interval',
            name='obsIntrval',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='ir',
            name='obsIr',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='it',
            name='obsIt',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='lotissement',
            name='obsLot',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='pays',
            name='obsPays',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='periode',
            name='obsPerio',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1),
        ),
        migrations.AlterField(
            model_name='prefecture',
            name='obsPref',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='quartier',
            name='obsQuart',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='obsRegion',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='residence',
            name='obsRes',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='rue',
            name='obsrue',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='situation',
            name='obsSit',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='solde',
            name='obsSit',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='taux_anc',
            name='obsTA',
            field=models.CharField(default='RAS', max_length=200),
        ),
        migrations.AlterField(
            model_name='tb',
            name='obsTb',
            field=models.CharField(default='RAS', max_length=200),
        ),
    ]
